language: node_js
node_js:
  - "10"
deploy:
  - provider: npm
    email: $DEPLOY_NPM_EMAIL
    api_key: $DEPLOY_NPM_API_KEY
    skip_cleanup: true
    on:
      tags: true
      branch: master
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
      branch: master
